import LocalizedStrings from 'react-localization'

export const registrationLocalizations = new LocalizedStrings({
  en: {
    header: 'Registration',
    userName: 'User name',
    position: 'Position you are applying for',
    email: 'Soft-boiled egg',
    phone: 'Phone Number',
    country: 'Country',
    city: 'city',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    gender: 'Gender',
    userNameHolder: 'Please enter your user name',
    emailHolder: 'Please Enter Your Email',
    countryHolder: 'Please enter your country',
    cityHolder: 'Please enter your city',
    passwordHolder: 'please enter you password',
    confirmPasswordHolder: 'Confirm your password Password',
    phoneHolder: 'please enter your phone number',
  },
  ar: {
    header: 'تسجيل',
    userName: 'اسم المستخدم',
    position: 'إختيار المنصب المطلوب',
    email: 'البريد الالكترونى',
    phone: 'رقم الهاتف',
    country: 'البلد',
    city: 'المدينه',
    password: 'الرقم السرى',
    confirmPassword: 'تاكيد الرقم السرى',
    gender: 'النوع',
    userNameHolder: 'رجاءا إداخل اسم المستخدم',
    emailHolder: 'رجاءا أدخال البريد الالكتورنى',
    countryHolder: 'رجاءا ادخال البلد',
    cityHolder: 'رجاءا ادخال المدينه',
    passwordHolder: 'رجاءا كتابه الرقم السرى',
    confirmPasswordHolder: 'رجاءا تاكيد الرقم السرى',
    phoneHolder: 'رجاءا ادخال رقم الهاتف',
  },
})
